name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v1
            - name: Elastic Beanstalk Deployment
              uses: kumarshivam12/Aws-ElasticBeanstalk@1.3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  EB-BUCKET-NAME: elasticbeanstalk-us-east-2-997800776769
                  APPLICATION-NAME: PetShopDockerMultistaget
                  EB-ENV-NAME: node-express-envt
                  AWS-REGION: us-east-2
                      
