name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v1

            - name: Elastic Beanstalk Deployment
              uses: kumarshivam12/Aws-ElasticBeanstalk@1.3
              with: 
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                EB-BUCKET-NAME:
                    description: Enter The Name of the S3 BUCKET
                APPLICATION-NAME:
                    description: Enter the name of the Elastick Beanstalk Application
                EB-ENV-NAME:
                    description: Enter the name of the Elastick Beanstalk Application
                AWS-REGION: 
                    description: Enter the Region